kind: ConfigMap
apiVersion: v1
metadata:
  name: ${SERVICE_NAME}-configs
data:
  # Configuration values can be set as key-value properties
  SERVICE__LOGLEVEL: ${SERVICE_LOGLEVEL}
  SERVICE__ENVIRONMENT: ${SERVICE_ENVIRONMENT}

  # Or set as complete file contents (even JSON!)
  keys: |
    service.name=${SERVICE_NAME}